name: Continuous Deployment

on:
  push:
    branches:
      - DEV
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    environment: "Production"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore ./GameGather.sln
        
      - name: Substitute appsettings.json entries
        uses: microsoft/variable-substitution@v1
        with:
          files: './src/GameGather.Api/appsettings.json'
        env:
          Email.ApiKeyPublic: ${{ secrets.EMAIL_API_KEY_PUBLIC }}
          Email.ApiKeyPrivate: ${{ secrets.EMAIL_API_KEY_PRIVATE }}
          Email.FromEmail: ${{ secrets.EMAIL_FROM_EMAIL }}
          Email.FromName: ${{ secrets.EMAIL_FROM_NAME }}
          Jwt.Issuer: "issuer"
          Jwt.Audience: "audience"
          Jwt.SecretKey: "ssupasde sdamek asdmk a kasdkasnd ksak ndkasnd ksa ndkasdn"
          Jwt.ValidFor: 120

      - name: Build
        run: dotnet build ./GameGather.sln --no-restore --configuration Release

      - name: Test
        run:  dotnet test ./GameGather.sln --configuration Release --no-restore --no-build

      - name: Publish
        run: dotnet publish ./src/GameGather.Api/GameGather.Api.csproj -c Release -o ./publish --no-restore --no-build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: 
      name: "Production"
      url: ${{ steps.deploy.outputs.webapp_url }}      
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./app-artifacts

      # - name: Create ZIP archive
      #   run: |
      #     cd ./app-artifacts
      #     zip -r ../gamegather-app.zip ./*

      # - name: Get current date
      #   id: date
      #   run: echo "date=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_OUTPUT

      # - name: Create Release
      #   id: create_release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: release-${{ steps.date.outputs.date }}
      #     name: Release ${{ steps.date.outputs.date }}
      #     files: gamegather-app.zip
      #     draft: false
      #     prerelease: false
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     body: |
      #       # Release notes
            
      #       Automatyczne wydanie po zmergeowaniu PR #${{ github.event.pull_request.number }}
            
      #       **PR Title**: ${{ github.event.pull_request.title }}
      #       **Merged by**: ${{ github.actor }}
      #       **Wdrożono na**: ${{ needs.terraform_prod.outputs.webapp_name }}

      - name: Login to Azure
        run: |
          echo "Logging in to Azure..."
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }} --output none
        
      - name: Deploy to Azure Web App
        id: deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          resource-group-name: ${{ vars.AZURE_RESOURCE_GROUP_NAME }}
          package: ./app-artifacts

      - name: Logout from Azure
        run: |
          az logout